controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /api/auth
    methods: [ 'POST' ]
api_doc:
    path: /documentation
    controller: api_platform.swagger_ui.action